CREATE TABLE IF NOT EXISTS vehicle_fuel (
    plate VARCHAR(20) PRIMARY KEY,
    fuel_level DECIMAL(5, 2) DEFAULT 100.00,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
